export const signInActionTypes = {
    REQUEST_ACTION: 'SIGN_IN_REQUEST_ACTION',
    SUCCESS_ACTION: 'SIGN_IN_SUCCESS_ACTION',
    FAILED_ACTION: 'SIGN_IN_FAILED_ACTION',
    SESSION_EXPIRED_ACTION: 'SESSION_EXPIRED_ACTION'
}

export const verifyEmailActionTypes = {
    REQUEST_ACTION: 'VERIFY_EMAIL_REQUEST_ACTION',
    SUCCESS_ACTION: 'VERIFY_EMAIL_SUCCESS_ACTION',
    FAILED_ACTION: 'VERIFY_EMAIL_FAILED_ACTION'
}

export const resendVerifyEmailActionTypes = {
    REQUEST_ACTION: 'RESEND_VERIFY_EMAIL_REQUEST_ACTION',
    SUCCESS_ACTION: 'RESEND_VERIFY_EMAIL_SUCCESS_ACTION',
    FAILED_ACTION: 'RESEND_VERIFY_EMAIL_FAILED_ACTION'
}

export const signUpActionTypes = {
    REQUEST_ACTION: 'SIGN_UP_REQUEST_ACTION',
    SUCCESS_ACTION: 'SIGN_UP_SUCCESS_ACTION',
    FAILED_ACTION: 'SIGN_UP_FAILED_ACTION'
}
