export const createBuyerRequest = {
    REQUEST_ACTION: 'CREATE_BUYER_REQUEST_REQUEST_ACTION',
    SUCCESS_ACTION: 'CREATE_BUYER_REQUEST_SUCCESS_ACTION',
    FAILED_ACTION: 'CREATE_BUYER_REQUEST_FAILED_ACTION'
}


export const getShipmentsRequest = {
    REQUEST_ACTION: 'QUERY_SHIPMENT_REQUEST_ACTION',
    SUCCESS_ACTION: 'QUERY_SHIPMENT_REQUESTS_SUCCESS_ACTION',
    FAILED_ACTION: 'QUERY_SHIPMENT_REQUESTS_FAILED_ACTION'
}

export const getTravellerRequest = {
    REQUEST_ACTION: 'QUERY_TRAVELLER_REQUEST_ACTION',
    SUCCESS_ACTION: 'QUERY_TRAVELLER_REQUESTS_SUCCESS_ACTION',
    FAILED_ACTION: 'QUERY_TRAVELLER_REQUESTS_FAILED_ACTION'
}

