export const getCommissionRate = {
    REQUEST_ACTION: 'GET_COMMISSION_RATE_REQUEST_ACTION',
    SUCCESS_ACTION: 'GET_COMMISSION_RATE_SUCCESS_ACTION',
    FAILED_ACTION: 'GET_COMMISSION_RATE_FAILED_ACTION'
}
