export const getNotificationsByUserActionType = {
    REQUEST_ACTION: 'GET_NOTIFICATIONS_REQUEST_ACTION',
    SUCCESS_ACTION: 'GET_NOTIFICATIONS_SUCCESS_ACTION',
    FAILED_ACTION: 'GET_NOTIFICATIONS_FAILED_ACTION'
}


