export const createOfferRequestActionType = {
    REQUEST_ACTION: 'CREATE_OFFER_REQUEST_REQUEST_ACTION',
    SUCCESS_ACTION: 'CREATE_OFFER_REQUEST_SUCCESS_ACTION',
    FAILED_ACTION: 'CREATE_OFFER_REQUEST_FAILED_ACTION'
}

export const getOffersActionType = {
    REQUEST_ACTION: 'GET_OFFERS_REQUEST_REQUEST_ACTION',
    SUCCESS_ACTION: 'GET_OFFERS_REQUEST_SUCCESS_ACTION',
    FAILED_ACTION: 'GET_OFFERS_REQUEST_FAILED_ACTION'
}
