export const getOrdersActionType = {
    REQUEST_ACTION: 'GET_ORDERS_REQUEST_ACTION',
    SUCCESS_ACTION: 'GET_ORDERS_SUCCESS_ACTION',
    FAILED_ACTION: 'GET_ORDERS_FAILED_ACTION'
}

export const getTrackingMethodsActionType = {
    REQUEST_ACTION: 'GET_TRACING_METHODS_REQUEST_ACTION',
    SUCCESS_ACTION: 'GET_TRACING_METHODS_SUCCESS_ACTION',
    FAILED_ACTION: 'GET_TRACING_METHODS_FAILED_ACTION'
}
