export const fcmActionTypes = {
    REQUEST_ACTION: 'SYNC_FCM_REQUEST_ACTION',
    SUCCESS_ACTION: 'SYNC_FCM_SUCCESS_ACTION',
    FAILED_ACTION: 'SYNC_FCM_FAILED_ACTION'
}

export const profileDetailsActionTypes = {
    REQUEST_ACTION: 'PROFILE_DETAILS_REQUEST_ACTION',
    SUCCESS_ACTION: 'PROFILE_DETAILS_SUCCESS_ACTION',
    FAILED_ACTION: 'PROFILE_DETAILS_FAILED_ACTION'
}

export const completeProfileActionTypes = {
    REQUEST_ACTION: 'COMPLETE_PROFILE_REQUEST_ACTION',
    SUCCESS_ACTION: 'COMPLETE_PROFILE_SUCCESS_ACTION',
    FAILED_ACTION: 'COMPLETE_PROFILE_FAILED_ACTION'
}
