export const resetActionTypes = {
    RESET_AUTH_ACTION: 'RESET_AUTH_ACTION',
    RESET_PROFILE_ACTION: 'RESET_PROFILE_ACTION',
    RESET_CREATE_BUYER_REQUEST: 'RESET_CREATE_BUYER_REQUEST',
    RESET_CREATE_SELLER_REQUEST: 'RESET_CREATE_SELLER_REQUEST',
    RESET_QUERY_SHIPMENT_REQUEST: "RESET_QUERY_SHIPMENT_REQUEST",
    RESET_QUERY_TRAVELLER_REQUESTS: "RESET_QUERY_TRAVELLER_REQUESTS",
    RESET_QUERY_BUYER_REQUESTS: "RESET_QUERY_BUYER_REQUESTS",
    RESET_COMMISSION_RATE_REQUEST: "RESET_COMMISSION_RATE_REQUEST",
    RESET_CREATE_OFFER_REQUEST: "RESET_CREATE_OFFER_REQUEST",
    RESET_GET_OFFER_LIST_REQUEST: "RESET_GET_OFFER_LIST_REQUEST",
    RESET_GET_NOTIFICATIONS_REQUEST: "RESET_GET_NOTIFICATIONS_REQUEST",
}
