export const createSellerRequest = {
    REQUEST_ACTION: 'CREATE_SELLER_REQUEST_REQUEST_ACTION',
    SUCCESS_ACTION: 'CREATE_SELLER_REQUEST_SUCCESS_ACTION',
    FAILED_ACTION: 'CREATE_SELLER_REQUEST_FAILED_ACTION'
}

export const queryOpenBuyerRequest = {
    REQUEST_ACTION: 'QUERY_OPEN_BUYER_REQUEST_ACTION',
    SUCCESS_ACTION: 'QUERY_OPEN_BUYER_REQUESTS_SUCCESS_ACTION',
    FAILED_ACTION: 'QUERY_OPEN_BUYER_REQUESTS_FAILED_ACTION'
}
